version: '3'

services:
  app:
    container_name: nextjs-app
    image: nextjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGO_URL=mongodb+srv://reciclajeJaviSRL:UGHaJtrkasEANGUN@reciclajesrldev.206bmci.mongodb.net/test
      - NEXTAUTH_SECRET=EstoEsUnaSeedSecreta
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodb-data: